### ISSUE TITLE
Unable to get past "RSI Login" page

### ISSUE THREAD

**Issue by Hotpocketdeath** [waibcam/RSI_Companion#2]
The plugin has stopped working for me and is perpetually stuck on the sign-in to RSI Account page and can't get past that point.  

Firefox 75

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://d679afc0-d4b3-4809-b5a0-a152a7ba83da/js/popper.min.js
Source Map URL: popper.min.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://d679afc0-d4b3-4809-b5a0-a152a7ba83da/js/bootstrap.bundle.min.js
Source Map URL: bootstrap.bundle.min.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://d679afc0-d4b3-4809-b5a0-a152a7ba83da/js/bootstrap-select.min.js
Source Map URL: bootstrap-select.min.js.map

**Comment by waibcam** [comment]
Hum, I don't have ny issue so it might be local.

Please, could you make sure the pluggin is at the latest version (0.2.6)?
If not, please upgrade it :)
If so, please, remove and reinstall it and see if it works again.

If it's still failing to work, please think about any software or addon that you setup recenty that could cause any issue with it.

Let me know!

**Comment by Hotpocketdeath** [comment]
I've already tried uninstalling and re-installing.  

I haven't made any changes since I first installed it other than the normal updates to Firefox.

**Comment by Hotpocketdeath** [comment]
Okay, you can close this.

We determined that there was an issue with my Star Citizen web account that was messing up a few things, including spectrum.  Star Citizen Support said they are aware of it and should have a permanent fix in the future, but the current workaround is to leave all my organizations and rejoin them.  Doing this fixed my spectrum issues as well as issues with the RSI companion add-on.

**Comment by waibcam** [comment]
Thanks for getting back on this! It's good for me to know that this may happen.
have a great week-end!
