### ISSUE TITLE
Companion not persistently connecting to RSI account

### ISSUE THREAD

**Issue by OrionOth** [waibcam/RSI_Companion#5]
This used to work fine. I am unsure whether this is just a temporary backend problem, but logging in to RSI and attempting to force the extension to load the account works intermittently, but quickly regresses to the default logged out state.
Addendum: Over the course of my testing it seems to have degraded to the point where it fails to function entirely.

[Companion Icon](https://i.imgur.com/rAMliFp.png)
[Companion Page](https://i.imgur.com/rFstaV4.png)
[RSI Account](https://i.imgur.com/RZbM1BL.png)

RSI Companion v0.2.12
Microsoft Edge 86.0.622.68 (Installed via Chrome Webstore)
Windows 10 Pro Version 20H2 (Build 19042.630)

EDIT: Checked Console readback.
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://kopamahnjkchmgjkoejfconipkclhibf/js/popper.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://kopamahnjkchmgjkoejfconipkclhibf/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://kopamahnjkchmgjkoejfconipkclhibf/js/bootstrap-select.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by OrionOth** [comment]
I managed to get in for just a second and the extension seems to be getting 404 errors as it attempts to `GET` player account avatars. I am a little concerned this is a problem identical to #2

**Comment by waibcam** [comment]
I'm not sure but this might be due to RSI server backend issue
![image](https://user-images.githubusercontent.com/7987454/99193397-ecf57480-2778-11eb-86f1-f506e20c1dd3.png)

**Comment by waibcam** [comment]
Obviously, this was due to RSI site. Everythin is back to nomrla now and we can close the issue.
Thanks for letting me know about it! I truly appreciated.
