### ISSUE TITLE
[BUG] Loaners are not displayed correctly

### ISSUE THREAD

**Issue by orchidObsessed** [waibcam/RSI_Companion#6]
Noticed it when purchasing the Hercules C2; the loaners for that ship are reported by RSI (and reflected in-game) as the MSR and the Caterpillar; on the app, it displays as the Starfarer Gemini, which is the loaner for the Hercules A2.

**Comment by waibcam** [comment]
Oh that's because it's new :) 
I used to be Gemini before the MSR has been release and I didn't pay  attention.

That should be fixed now, can you "Refresh" your list in app and let me know?

**Comment by orchidObsessed** [comment]
It's 50% fixed - the MSR now displays in the app, but instead of the caterpillar, it shows the herald and freelancer.

Also now worries about the bug - I just didn't know if you were aware, I knew that the MSR loaner change was very new. :)

**Comment by waibcam** [comment]
oops, my bad. Please try again :)

**Comment by orchidObsessed** [comment]
It is now displaying correctly! I'll go ahead and mark the issue closed :)

**Comment by waibcam** [comment]
Thank you again for your report. I don't have much and I truly appreciate it!
